[microk8s_masters]
master-1 ansible_host=10.102.13.162


[microk8s_workers]
worker-1 ansible_host=10.102.11.4
worker-2 ansible_host=10.102.13.94

[microk8s_cluster:children]
microk8s_masters
microk8s_workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/openstack-cluster-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
