# K3s Cluster Inventory
# Editează IP-urile și hostname-urile conform infrastructurii tale

[k3s_masters]
master-node ansible_host=10.102.11.24

[k3s_workers]
worker-node-1 ansible_host=10.102.12.154
worker-node-2 ansible_host=10.102.11.177
worker-node-3 ansible_host=10.102.12.241
worker-node-4 ansible_host=10.102.11.50
worker-node-5 ansible_host=10.102.14.101


# Grup care conține toate nodurile
[k3s_cluster:children]
k3s_masters
k3s_workers

# Variabile pentru toate nodurile din cluster
[k3s_cluster:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
