all:
  children:
    windows_ad:
      hosts:
        win2022-ad-01:
          ansible_host: 10.102.11.81
          ansible_user: Administrator
          ansible_password: "123windowsserver#"
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
          ansible_winrm_transport: ntlm
